import { authenticated, endpoint, json, parseBody } from '../../../../../server/http.ts';
import { requestLimit } from '../../../../../server/limits.ts';
import { InterviewQuestionActionSchema } from '../../../../../contracts/memory.ts';

/** Questions are generated by the agent and answered by the next chat message. */
export async function GET(request: Request) {
  return endpoint(async () => {
    const s = await authenticated(request);
    await requestLimit(s.db, s.ownerId);
    const workspace = await s.interview.get(s.ownerId);
    return json({ questions: await s.memoryQuestions.list(s.ownerId, workspace.interview.id) });
  });
}

export async function POST(request: Request) {
  return endpoint(async () => {
    const s = await authenticated(request);
    await requestLimit(s.db, s.ownerId);
    const input = await parseBody(request, InterviewQuestionActionSchema);
    const question =
      input.action === 'skip'
        ? await s.memoryQuestions.skip(
            s.ownerId,
            input.questionId,
            input.expectedVersion,
            input.commandId,
          )
        : input.action === 'dismiss'
          ? await s.memoryQuestions.dismiss(
              s.ownerId,
              input.questionId,
              input.expectedVersion,
              input.commandId,
            )
          : await s.memoryQuestions.block(
              s.ownerId,
              input.questionId,
              input.expectedVersion,
              input.commandId,
            );
    return json({ question });
  });
}
